name: CI/CD to Docker Hub and Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    env:
      FRONTEND_IMAGE: "moawiz/travel-frontend:${{ github.sha }}"
      BACKEND_IMAGE: "moawiz/travel-backend:${{ github.sha }}"
      MINIKUBE_DRIVER: docker  # Switch to Docker driver (simpler than Hyper-V)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup Docker and Minikube
        shell: powershell
        run: |
          # Stop and remove all containers (including paused ones)
          docker ps -aq | ForEach-Object { docker rm -f $_ }
          
          # Reset Minikube
          minikube delete --all --purge
          Remove-Item -Path "$HOME\.minikube" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Start Minikube (Docker Driver)
        shell: powershell
        run: |
          # Ensure Docker is running
          Start-Service docker
          
          # Start Minikube with Docker driver
          minikube start --driver=docker --cpus=2 --memory=4096 --disk-size=20g
          minikube addons enable ingress
          minikube addons enable metrics-server

      - name: Verify Minikube and Docker
        shell: powershell
        run: |
          # Check Docker
          docker ps
          
          # Check Minikube
          minikube status
          kubectl get pods -A

      - name: Build and Push Images
        uses: docker/build-push-action@v5
        with:
          context: ./travel-to-pakistan/frontend
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}

      - name: Deploy to Kubernetes
        shell: powershell
        run: |
          kubectl apply -f ./travel-to-pakistan/mongodb/ -n travel-app
          kubectl apply -f ./travel-to-pakistan/backend/ -n travel-app
          kubectl apply -f ./travel-to-pakistan/frontend/ -n travel-app
          minikube service list -n travel-app