name: CI/CD to Docker Hub and Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    env:
      FRONTEND_IMAGE: moawiz/travel-frontend:latest
      BACKEND_IMAGE: moawiz/travel-backend:latest
      MONGODB_IMAGE: moawiz/travel-mongodb:latest
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: |
          docker buildx build --load -t $FRONTEND_IMAGE "./travel\ to\ pakistan/frontend"
          docker buildx build --load -t $BACKEND_IMAGE "./travel\ to\ pakistan/backend"
          docker buildx build --load -t $MONGODB_IMAGE "./travel\ to\ pakistan/mongodb"

      - name: Push Docker Images
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $FRONTEND_IMAGE
          docker push $BACKEND_IMAGE
          docker push $MONGODB_IMAGE

      - name: Deploy to Minikube
        run: |
          kubectl apply -f "./travel to pakistan/mongodb"
          kubectl apply -f "./travel to pakistan/backend"
          kubectl apply -f "./travel to pakistan/frontend"
