name: CI/CD to Docker Hub and Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker Hub image tags
        run: |
          echo "FRONTEND_IMAGE=moawiz/frontend:latest" >> $GITHUB_ENV
          echo "BACKEND_IMAGE=moawiz/backend:latest" >> $GITHUB_ENV
          echo "MONGODB_IMAGE=moawiz/mongodb:latest" >> $GITHUB_ENV

      - name: Build Docker Images
        run: |
          docker build -t $FRONTEND_IMAGE "./travel to pakistan/frontend"
          docker build -t $BACKEND_IMAGE "./travel to pakistan/backend"
          docker build -t $MONGODB_IMAGE "./travel to pakistan/mongodb"

      - name: Push Docker Images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push $FRONTEND_IMAGE
          docker push $BACKEND_IMAGE
          docker push $MONGODB_IMAGE

      - name: Deploy to Minikube
        run: |
          kubectl apply -f "./travel to pakistan/mongodb"
          kubectl apply -f "./travel to pakistan/backend"
          kubectl apply -f "./travel to pakistan/frontend"
